/*Material*/

CREATE TABLE MATERIAL (
    codigo_m VARCHAR2(10) CONSTRAINT PK_MATERIAL PRIMARY KEY,
    descripcion VARCHAR2(100) NOT NULL
);

CREATE CLUSTER EDIFI_DISP
    (codigo_ed VARCHAR2(10))
    SIZE 3000 HASHKEYS 25;

/*Edificio*/ 

CREATE TABLE Edificio (
    codigo_ed VARCHAR2(10) CONSTRAINT PK_EDIFICIO PRIMARY KEY,

    calle VARCHAR2(50) NOT NULL,

    numero NUMBER(10, 0) NOT NULL,

    codigo_postal NUMBER(10, 0) NOT NULL,

    ciudad VARCHAR2(30) NOT NULL,

    superficie REAL CHECK (superficie >= 0) NOT NULL,

    codigo_c VARCHAR2(10) NOT NULL

	/*CONSTRAINT FK_EDIFICIO_CARGO FOREIGN KEY (codigo_c) REFERENCES Cargo(codigo_c) DEFERRABLE INITIALLY DEFERRED*/

)
CLUSTER EDIFI_DISP(codigo_ed);
 
/*Almacen*/

CREATE TABLE Almacen (
    codigo_m VARCHAR2(10),
    codigo_ed VARCHAR2(10),
    fecha DATE NOT NULL,
    cantidad NUMBER(10, 0) CHECK (cantidad >= 0) NOT NULL,
    CONSTRAINT PK_ALMACEN PRIMARY KEY (codigo_ed, codigo_m),
    CONSTRAINT FK_ALMACEN_MATERIAL FOREIGN KEY (codigo_m) REFERENCES MATERIAL(codigo_m) ON DELETE CASCADE
    DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT FK_ALMACEN_EDIFICIO FOREIGN KEY (codigo_ed) REFERENCES EDIFICIO(codigo_ed) DEFERRABLE INITIALLY DEFERRED
);

/*Parking y plazas: primero creamos el clúster para 25 párkings cada uno de ellos con 40 plazas. */
CREATE CLUSTER PARKING_PLAZAS
    (codigo_plz VARCHAR2(10), codigo_p VARCHAR2(10))
    HASHKEYS 25;

/*Parking */

CREATE TABLE PARKING(
    superficie NUMBER(10, 0) CHECK (superficie >= 0) NOT NULL,
    codigo_ed VARCHAR2(10) NOT NULL,
    codigo_p VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_PARKING PRIMARY KEY (codigo_ed),
    CONSTRAINT FK_PARKING_EDFICIO FOREIGN KEY (codigo_ed) REFERENCES Edificio(codigo_ed) ON DELETE CASCADE)
    
CLUSTER PARKING_PLAZAS(codigo_ed, codigo_p);

/* Plazas */

CREATE TABLE PLAZAS(
    codigo_plz VARCHAR2(10),
    codigo_ed VARCHAR2(10),
    CONSTRAINT PK_PLAZAS PRIMARY KEY (codigo_plz, codigo_ed),
    CONSTRAINT FK_PLAZAS_PARKING FOREIGN KEY (codigo_ed) REFERENCES PARKING(codigo_ed) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED)
    
CLUSTER PARKING_PLAZAS(codigo_plz,codigo_ed);

/* Simples */ 

CREATE TABLE SIMPLES(
    codigo_plz VARCHAR2(10),
    codigo_ed VARCHAR2(10),
    CONSTRAINT PK_SIMPLES PRIMARY KEY (codigo_plz, codigo_ed),
    CONSTRAINT FK_SIMPLES_PLAZAS FOREIGN KEY (codigo_plz, codigo_ed) REFERENCES PLAZAS(codigo_plz, codigo_ed) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
    
)
ORGANIZATION INDEX
TABLESPACE USERS;

/*Dobles*/ 

CREATE TABLE DOBLES (
    codigo_plz VARCHAR2(10),
    codigo_ed VARCHAR2(10),
    CONSTRAINT PK_DOBLES PRIMARY KEY (codigo_plz, codigo_ed),
    CONSTRAINT FK_DOBLES_PLAZAS FOREIGN KEY (codigo_plz, codigo_ed) REFERENCES Plazas(codigo_plz, codigo_ed) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
)
ORGANIZATION INDEX
TABLESPACE USERS;

/*Empleado*/

CREATE TABLE EMPLEADO(
    numero NUMBER(10, 0),
    DNI VARCHAR2(10) NOT NULL CONSTRAINT DNI_UNICO UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    calle VARCHAR2(50) NOT NULL,
    numero_calle NUMBER(10, 0) NOT NULL,
    codigo_postal NUMBER(10, 0) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    codigo_plz VARCHAR2(10) NOT NULL CONSTRAINT CODIGO_PLZ_UNICO UNIQUE,
    codigo_ed VARCHAR2(10) NOT NULL,
    CONSTRAINT FECHA_FIN_OK CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (numero),
    CONSTRAINT FK_EMPLEADO_DOBLES FOREIGN KEY (codigo_plz,codigo_ed) REFERENCES Dobles(codigo_plz, codigo_ed) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

/*Cargo*/

CREATE TABLE Cargo (
    código_c VARCHAR2(10) CONSTRAINT PK_CODIGO_CARGO PRIMARY KEY,
    descripción VARCHAR2(100) NOT NULL CONSTRAINT DESCRIPCION_UNICA UNIQUE,
    nombre VARCHAR2(100) NOT NULL CONSTRAINT NOMBRE_UNICO UNIQUE,
    numero_em NUMBER(10, 0) NOT NULL,
    CONSTRAINT FK_CARGO_EMPLEADO FOREIGN KEY (numero_em) REFERENCES Empleado(numero) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

ALTER TABLE EDIFICIO
ADD CONSTRAINT FK_EDIFICIO_CARGO FOREIGN KEY (codigo_c) REFERENCES Cargo(código_c) DEFERRABLE INITIALLY DEFERRED;

/*Dependencia*/ 
CREATE TABLE DEPENDENCIA (
    codigo_d VARCHAR2(10),
    codigo_ed VARCHAR2(10),
    codigo_c VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_DEPENDENCIA PRIMARY KEY (codigo_d, codigo_ed),
    CONSTRAINT FK_DEPENDENCIA_EDIFICIO FOREIGN KEY (codigo_ed) REFERENCES Edificio(codigo_ed),
    CONSTRAINT FK_DEPENDENCIA_CARGO FOREIGN KEY (codigo_c) REFERENCES Cargo(código_c) DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX INDEX_COD_C ON DEPENDENCIA (CODIGO_C) TABLESPACE USERS;

/*Restringido*/ 

CREATE TABLE Restringido (
    codigo_d VARCHAR2(10),
    codigo_ed VARCHAR2(10),
    CONSTRAINT PK_RESTRINGIDO PRIMARY KEY (codigo_d, codigo_ed),
    CONSTRAINT FK_RESTRINGIDO_DEPENDENCIA FOREIGN KEY (codigo_d, codigo_ed) REFERENCES Dependencia(codigo_d,codigo_ed) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
)ORGANIZATION INDEX
TABLESPACE USERS;

/*Particular*/ 

CREATE TABLE Particular (
    codigo_d VARCHAR2(10),
    numero NUMBER(10, 0),
    codigo_ed VARCHAR2(10),
    CONSTRAINT PK_PARTICULAR PRIMARY KEY (codigo_d, codigo_ed),
    CONSTRAINT FK_PARTICULAR_DEPENDENCIA FOREIGN KEY (codigo_d, codigo_ed) REFERENCES Dependencia(codigo_d,codigo_ed) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT FK_PARTICULAR_EMPLEADO FOREIGN KEY (numero) REFERENCES Empleado(numero) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
)
ORGANIZATION INDEX TABLESPACE USERS;
CREATE UNIQUE INDEX INDEX_NUM ON PARTICULAR (NUMERO) TABLESPACE USERS;
        
/*Uso res*/

CREATE TABLE USO_RES (
    numero NUMBER(10, 0),
    codigo_d VARCHAR2(10),
    codigo_ed VARCHAR2(10),
    CONSTRAINT PK_USO_RES PRIMARY KEY (numero, codigo_d, codigo_ed),
    CONSTRAINT FK_USO_RES_DEPENDENCIA FOREIGN KEY (codigo_d, codigo_ed) REFERENCES Dependencia(codigo_d, codigo_ed) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT FK_USO_RES_EMPLEADO FOREIGN KEY (numero) REFERENCES Empleado(numero) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED);
    CREATE UNIQUE INDEX INDEX_NUMERO ON USO_RES (NUMERO);
    
/*Mueble*/

CREATE TABLE Mueble (
    codigo_mu VARCHAR2(10),
    tipo VARCHAR2(10) NOT NULL,
    estado VARCHAR2(20) NOT NULL,
    codigo_d VARCHAR2(10) NOT NULL,
    codigo_ed VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_MUEBLE PRIMARY KEY (codigo_mu),
    CONSTRAINT FK_MUEBLE_DEPENDENCIA FOREIGN KEY (codigo_d, codigo_ed) REFERENCES DEPENDENCIA(codigo_d, codigo_ed)  DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX INDEX_STATUS ON MUEBLE (ESTADO);

/* Aparato */

CREATE TABLE APARATO(
    modelo VARCHAR2(50) NOT NULL,
    marca VARCHAR2(20) NOT NULL,
    fecha_compra DATE NOT NULL,
    fecha_fin_garantia DATE NOT NULL,
    codigo_mu VARCHAR2(10),
    tiempo_garantia NUMBER(10, 0),
    CONSTRAINT PK_APARATO PRIMARY KEY (codigo_mu),
    CONSTRAINT FK_APARATO_MUEBLE FOREIGN KEY (codigo_mu) REFERENCES Mueble(codigo_mu) ON DELETE CASCADE  DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX INDEX_COD_MOD ON APARATO (CODIGO_MU,MODELO);
CREATE INDEX INDEX_FECHA ON APARATO (FECHA_FIN_GARANTIA);


