CREATE TABLE Materiales (
    material VARCHAR(50)
);
INSERT INTO  Materiales(material) VALUES('Papel A4');
  INSERT INTO  Materiales(material) VALUES('Bolígrafos de gel');
  INSERT INTO  Materiales(material) VALUES('Notas adhesivas');
  INSERT INTO  Materiales(material) VALUES('Grapas');
  INSERT INTO  Materiales(material) VALUES('Clips metálicos');
  INSERT INTO  Materiales(material) VALUES('Cinta adhesiva');
  INSERT INTO  Materiales(material) VALUES('Calculadora');
  INSERT INTO  Materiales(material) VALUES('Agenda');
  INSERT INTO  Materiales(material) VALUES('Folios de colores');
  INSERT INTO  Materiales(material) VALUES('Marcadores de pizarra blanca');
  INSERT INTO  Materiales(material) VALUES('Rotuladores permanentes');
  INSERT INTO  Materiales(material) VALUES('Tijeras');
  INSERT INTO  Materiales(material) VALUES('Gomas de borrar');
  INSERT INTO  Materiales(material) VALUES('Lápices de colores');
  INSERT INTO  Materiales(material) VALUES('Carpeta archivadora');
  INSERT INTO  Materiales(material) VALUES('Portafolios');
  INSERT INTO  Materiales(material) VALUES('Portaminas');
  INSERT INTO  Materiales(material) VALUES('Cuadernos de espiral');
  INSERT INTO  Materiales(material) VALUES('Calculadora científica');
  INSERT INTO  Materiales(material) VALUES('Corrector líquido');
  INSERT INTO  Materiales(material) VALUES('Regla de metal');
  INSERT INTO  Materiales(material) VALUES('Post-its de colores');
  INSERT INTO  Materiales(material) VALUES('Pegamento en barra');
  INSERT INTO  Materiales(material) VALUES('Carpetas colgantes');
  INSERT INTO  Materiales(material) VALUES('Sillas ergonómicas');
  INSERT INTO  Materiales(material) VALUES('Escritorio ajustable');
  INSERT INTO  Materiales(material) VALUES('Lámpara de escritorio');
  INSERT INTO  Materiales(material) VALUES('Cajas de almacenamiento');
  INSERT INTO  Materiales(material) VALUES('Estanterías modulares');
  INSERT INTO  Materiales(material) VALUES('Auriculares con cancelación de ruido');
  INSERT INTO  Materiales(material) VALUES('Alfombrilla de ratón');
  INSERT INTO  Materiales(material) VALUES('Tarjetero');
  INSERT INTO  Materiales(material) VALUES('Organizador de cables');
  INSERT INTO  Materiales(material) VALUES('Cubiletes para bolígrafos');
  INSERT INTO  Materiales(material) VALUES('Bandejas de entrada');
  INSERT INTO  Materiales(material) VALUES('Papelera de reciclaje');
  INSERT INTO  Materiales(material) VALUES('Tablón de anuncios');
  INSERT INTO  Materiales(material) VALUES('Sellos de fecha');
  INSERT INTO  Materiales(material) VALUES('Archivadores de documentos');
  INSERT INTO  Materiales(material) VALUES('Separadores para carpetas');
  INSERT INTO  Materiales(material) VALUES('Calculadora financiera');
  INSERT INTO  Materiales(material) VALUES('Silla de visitante');
  INSERT INTO  Materiales(material) VALUES('Paragüero');
  INSERT INTO  Materiales(material) VALUES('Caja fuerte portátil');
  INSERT INTO  Materiales(material) VALUES('Reloj de pared');
  INSERT INTO  Materiales(material) VALUES('Taza para lápices');
  INSERT INTO  Materiales(material) VALUES('Engrampadora eléctrica');
  INSERT INTO  Materiales(material) VALUES('Monitor de doble pantalla');